name: "HomeSeer Z-Wave Sensor"
packageKey: "homeseer-zwave-sensor"
description: "This driver extends the basic zwave functionality to include additional vendor specific parameters"
vendorSupportInformation: >-
   'This driver require a documented device to work properly.<br /><br />
    <a href="https://community.smartthings.com/t/beta-edge-drivers-for-homeseer-devices/">SmartThings Community discussion</a><br /><br />
    <a href="https://github.com/jshessen/SmartThingsEdgeDrivers/blob/main/README.md">GitHub Repository</a>'
permissions:
  zwave: {}