name: publish-smartthings-driver

on:
  workflow_call:
    inputs:
      driver:
        description: "SmartThings driver name"
        required: true
        type: string
      path:
        description: "Folder name of the driver"
        required: true
        type: string
      label:
        description: "name in config.yaml"
        required: true
        type: string
      pkgkey:
        description: packageKey in config.yaml
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
        default: beta
  workflow_dispatch:
    inputs:
      driver:
        description: "Folder name of the driver"
        required: true
        type: string
      path:
        description: "Folder name of the driver"
        required: true
        type: string
      label:
        description: "name in config.yaml"
        required: true
        type: string
      pkgkey:
        description: packageKey in config.yaml
        required: true
        type: string
      environment:
        description: Environment
        required: true
        type: string
        default: beta

jobs:
  modify-config:
    name: "Modify Driver Config"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@v3
      
      - name: "Define 'main' Branch Environment Variables"
        if: ${{ inputs.environment == 'main' }}
        run: |
          echo "LABEL=${{ inputs.label }}" >> $GITHUB_ENV  
          echo "PKG_KEY=${{ inputs.pkgkey }}" >> $GITHUB_ENV
        
      - name: "Define Branch Environment Variables"
        if: ${{ inputs.environment == 'beta' }}
        run: |
          echo "LABEL=${{ inputs.label }} (beta)" >> $GITHUB_ENV  
          echo "PKG_KEY=${{ inputs.pkgkey }}-beta" >> $GITHUB_ENV
          
      - name: "Load config.yaml from Cache"
        id: cache-config
        uses: actions/cache@v3
        with:
          path: "${{ inputs.path }}/${{ inputs.driver }}/config.yaml"
          key: ${{ inputs.pkgkey }}-${{ inputs.environment }}
          
      - name: "Generate config.yaml using Handlebars Template"
        if: steps.cache-config.outputs.cache-hit != 'true'
        uses: pedrolamas/handlebars-action@v2.1.0
        with:
          files: './.github/workflows/templates/config.yaml.template'
          output-filename: "${{ inputs.path }}/${{ inputs.driver }}/config.yaml"
        env:
          GITHUB: "${{ github.server_url }}/${{ github.repository }}"
          COMMUNITY_LINK: "https://community.smartthings.com/t/beta-edge-drivers-for-homeseer-devices/"
          
  publish:
    name: "Publish Driver"
    needs: modify-config
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: "Fetching Repository Contents"
        uses: actions/checkout@v3
        
      - name: "Load config.yaml from Cache"
        id: cache-config
        uses: actions/cache@v3
        with:
          path: "${{ inputs.path }}/${{ inputs.driver }}/config.yaml"
          key: ${{ inputs.pkgkey }}-${{ inputs.environment }}
          
      - name: "Load smartthings-cli From Cache"
        id: stcli
        uses: actions/cache@v3        
        with:
          path: smartthings
          key: stcli-latest
          
      - name: "Download smartthings-cli"
        if: steps.stcli.outputs.cache-hit != 'true'
        run: wget https://github.com/SmartThingsCommunity/smartthings-cli/releases/latest/download/smartthings-linux-x64.tar.gz -O - | tar -xz
        
      - name: "Publish - edge:drivers:package"
        run: ./smartthings edge:drivers:package ${{ inputs.path }}/${{ inputs.driver }} --channel=${{ secrets.SMARTTHINGS_CHANNEL }}
        env:
          SMARTTHINGS_TOKEN: ${{ secrets.SMARTTHINGS_TOKEN }}