name: Release

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        required: true
        type: string
        default: beta
  workflow_dispatch:
      environment:
        description: Environment
        required: true
        type: string
        default: beta

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Semantic Release"
        id: release-semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}